ci: Upgrade docs deployment actions
Seeing this error when deploying docs:

    Error: Missing download info for actions/upload-artifact@v3

It's probably upload-pages-artifact@v1 being deprecated. So upgrade
that. And upgrade the other ones as well - might as well.

Signed-off-by: Daniel Xu <dxu@dxuuu.xyz>