Fix diff parsing for one-line pre or post-image
I saw a crash:

	thread 'main' panicked at src/parser.rs:182:21:
	internal error: entered unreachable code: Unexpected non-zero left-hand-side of git diff header. Expected 0.

Turns out that given hunk header

	@@ -1,2 +3 @@

commit 3e9c247 (oneliners have deviant headers when adding files
(#12), 2022-08-18) interprets 3 as the length of the post-image.
This is wrong; 3 is the line where the post-image starts.
The length is implied to be 1 if omitted like.

Such one-line diffs can be created with

	$ printf '0\n1\n' > 1
	$ printf '0\n2\n2' > 2
	$ git diff --no-index 1 2 -U0
	diff --git a/1 b/2
	index d00491f..0cfbf08 100644
	--- a/1
	+++ b/2
	@@ -2 +2 @@
	-1
	+2